name: directory_router
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.4.2
  shelf: ^1.4.1
  http: ^1.1.0
  yaml: ^3.1.2
  watcher: ^1.1.0
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.1
