name: directory_router
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^1.6.0
  shelf: ^0.7.5
  http: ^0.12.2
  yaml: ^2.2.1
  watcher: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  pedantic: ^1.9.0
